### PR TITLE
fix redirect links

### PR DESCRIPTION
**Pull request by eksperimental**
previously, in #5, I overlooked the fact that the new index.html files were in sub-folders.
now all redirection uses absolute links.

sorry about that.

### CODE REVIEW

**Comment by josevalim** [comment]
The issue is that: because we automatically generate those directories, they are going to be deleted on every release.

**Comment by josevalim** [comment]
Ok, I have updated the build scripts and merged, we are good to go!

**Comment by eksperimental** [comment]
Sorry Jose, but I cannot see the changes of this last pull request.
Maybe when you updated the script you used the index.html files from my first pull request.

**Comment by eksperimental** [comment]
sorry @josevalim but this is still not fixed.
I think your script that creates the nightly build may have overwritten it,

https://github.com/elixir-lang/docs/blob/gh-pages/stable/index.html
sould read 
 url=/docs.html#stable"
not
 url=../docs.html#stable"

CHeeerrrs!

**Pull request merged**
